version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    groups:
      all:
        patterns: ["*"]
    schedule:
      interval: monthly
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      all:
        patterns: ["*"]
    schedule:
      interval: monthly
