defaults:
  repo: nobe4/ln-source

links:
  - from: script/tag-release

  - from: go/script/lint
    to: script/lint

  - from: go/script/test
    to: script/test

  - from: go/.golangci.yaml
    to: .golangci.yaml

  # Do this bootstrap later
  # - from:
  #     repo: nobe4/ln-source
  #     path: .github/workflows/link.yaml
  #   to:
  #     path: .github/workflows/link.yaml
