name: ln
description: Link files between repositorie

inputs:
  token:
    description: GitHub token to authenticate with.
    required: false
  config-path:
    description: Relative path to the config file.
    required: true
    default: ./ln-config.yaml

runs:
  using: node20
  main: dist/index.js
