name: ln
description: Link files between repositories

inputs:
  token:
    description: GitHub token to authenticate with.
    required: false
    default: ${{ github.token }}
  config-path:
    description: Relative path to the config file.
    required: true
    default: ln-config.yaml
  noop:
    description: Only load the data, but don't update anything.
    required: true
    default: "false"

runs:
  using: node20
  main: dist/index.js
