name: ln
description: Link files between repositories

inputs:
  noop:
    description: Load the data, but don't update anything.
    required: true
    default: "false"

  # See https://github.com/nobe4/action-ln/blob/main/docs/configuration.md
  config:
    description: Relative path to the config file.
    required: true
    default: ".ln-config.yaml"
    # E.g.
    #  - ".github/ln-config.yaml"
    #  - "config/ln/config.yaml"

  # See https://github.com/nobe4/action-ln/blob/main/docs/authentication.md
  token:
    description: GitHub token to authenticate with.
    required: false
    default: "${{ github.token }}"

  app_id:
    description: GitHub App ID to authenticate with
    required: false

  app_private_key:
    description: GitHub App Private Key to authenticate with
    required: false

  app_install_id:
    description: GitHub App installation ID to authenticate with
    required: false

runs:
  using: node20
  main: dist/index.js
