#!/usr/bin/env bash
#/ usage: build.sh [-h] [VERSION]

set -e

show_help() { grep ^#/ <"${0}" | cut -c4- ; }
[[ "$*" == "-h" ]] && show_help && exit 0

VERSION="${1:-dev}"

build (){
	os="${1}"
	arch="${2}"
	bin="main-${os}-${arch}-${VERSION}"

	echo "building ${bin}..."
	CGO_ENABLED=0 GOOS="${os}" GOARCH="${arch}" \
		go build \
			-ldflags="-s -w" \
			-o "./dist/${bin}" \
			./cmd/action-ln/
}

rm -f ./dist/main-*
build linux arm64
build linux amd64

sed -i 's/const version = ".\+/const version = "'"${VERSION}"'";/g' ./dist/index.js

