# This file is a valid configuration file augmented for testing purpose.
#
# It demonstrats all the possible configuration cases while being part of the
# test suite. See config.TestConfigParseAll.

# In most cases, only `from` if fully specified, since both `from` and `to` are
# parsed _exactly_ the same way.

# The default is fixed to avoid embiguity.
# It corresponds also to the current repo.
defaults:
  link:
    from:
      owner: from_owner
      repo: from_repo
    to:
      owner: to_owner
      repo: to_repo

links:
  # wants nothing
  -

  # want: from_owner/from_repo:a.txt@ -> to_owner/to_repo:b.txt@
  - from: a.txt
    to: b.txt

  # want: from_owner/from_repo:a.txt@ref -> to_owner/to_repo:b.txt@
  - from: a.txt@ref
    to: b.txt

  # want: own/rep:a.txt@ref -> to_owner/to_repo:b.txt@
  - from: own/rep:a.txt@ref
    to: b.txt

  # want: own/rep:a.txt@ref -> to_owner/to_repo:b.txt@
  - from: https://github.com/own/rep/blob/ref/a.txt
    to: b.txt

  # want: own/rep:a.txt@ref -> to_owner/to_repo:b.txt@
  - from: own/rep/blob/ref/a.txt
    to: b.txt

  # want: from_owner/from_repo:a.txt@ -> own/rep:a.txt@
  - from: a.txt
    # needs quotes, because YAML wants to read the second : as a mapping.
    to: "own/rep:"

  # want: from_owner/from_repo:a.txt@ -> own/rep:a.txt@ref
  - from: a.txt
    to: own/rep:@ref

  # want: from_owner/from_repo:a.txt@ -> own/rep:a.txt@
  - from: a.txt
    to:
      repo: own/rep

  # want: from_owner/from_repo:a.txt@main -> to_owner/to_repo:b.txt@
  - from:
      path: a.txt
      ref: main
    to: b.txt

  # want: own/rep:a.txt@main -> to_owner/to_repo:b.txt@
  - from:
      repo: own/rep
      path: a.txt
      ref: main
    to: b.txt

  # want: own/rep:a.txt@main -> to_owner/to_repo:b.txt@
  - from:
      owner: own
      repo: rep
      path: a.txt
      ref: main
    to: b.txt

  # want: from_owner/from_repo:a.txt@ -> own/rep:a.txt@
  # want: from_owner/from_repo:b.txt@ -> own/rep:b.txt@
  # want: from_owner/from_repo:c.txt@ -> own/rep:c.txt@
  - from:
      - a.txt
      - b.txt
      - c.txt
    to:
      repo: own/rep

  # want: from_owner/from_repo:a.txt@ -> own/rep:a.txt@
  # want: own/rep:b.txt@ -> own/rep:b.txt@
  # want: from_owner/from_repo:path/to/c.txt@ -> own/rep:path/to/c.txt@
  - from:
      - a.txt
      - path: b.txt
        repo: own/rep
      - path/to/c.txt
    to:
      repo: own/rep

  # want: from_owner/from_repo:a.txt@ -> to_owner/to_repo:c.txt@
  # want: own/rep:b.txt@ -> to_owner/to_repo:c.txt@
  - from:
      - a.txt
      - path: b.txt
        repo: own/rep
    to: c.txt

  # TODO: this is not yet supported
  # # want: from_owner/from_repo:a.txt@ -> owner/to_repo:a.txt@
  # # want: from_owner/from_repo:b.txt@ -> owner/to_repo:b.txt@
  # - from: *.txt
