name: edge

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-edge:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: |
          git push -d origin edge || true
          git checkout -b edge

          npm clean-install
          npm run all
          npm run build
          npm run build:add

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "chore(dist): automatically publish on edge"
          git push --force origin edge
