name: ln

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ln:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: nobe4/action-ln@v0
        with:
          noop: true # until I get a github app setup
          app-id: ${{ secrets.ACTION_LN_APP_ID }}
          app-private-key: ${{ secrets.ACTION_LN_APP_PRIVATE_KEY }}
          app-install-id: ${{ secrets.ACTION_LN_APP_INSTALL_ID }}
