name: release

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - run: npm clean-install

      - run: npm run all

      # TODO: delete all but the dist folder

      - run: gh release create --generate-notes --verify-tag --latest ${{ github.ref_name }}

      - uses: actions/publish-immutable-action@0.0.3
